kind: pipeline
name: deployment

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: deploy
    image: docker/compose:1.23.2
    environment:
      PLEX_CLAIM:
        from_secret: PLEX_CLAIM
      PLEX_ADVERTISE_IP:
        from_secret: PLEX_ADVERTISE_IP
      AZIRE_USERNAME:
        from_secret: AZIRE_USERNAME
      AZIRE_PASSWORD:
        from_secret: AZIRE_PASSWORD
      AZIRE_LOCATION:
        from_secret: AZIRE_LOCATION
    commands:
      - docker-compose down ftpd
      - docker-compose up ftpd
    volumes:
    - name: dockersock
      path: /var/run/docker.sock


volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
