kind: pipeline
name: deployment

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: deploy
    image: docker/compose:1.23.2
    environment:
      PLEX_CLAIM:
        from_secret: PLEX_CLAIM
      PLEX_ADVERTISE_IP:
        from_secret: PLEX_ADVERTISE_IP
      AZIRE_USERNAME:
        from_secret: AZIRE_USERNAME
      AZIRE_PASSWORD:
        from_secret: AZIRE_PASSWORD
      AZIRE_LOCATION:
        from_secret: AZIRE_LOCATION
      FTP_USER_NAME:
        from_secret: FTP_USER_NAME
      FTP_USER_PASS:
        from_secret: FTP_USER_PASS
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL:
        from_secret: WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL
    commands:
      - COMPOSE_PROJECT_NAME=project-media docker-compose up -d --build
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  # - name: deploy-drone
  #   image: docker/compose:1.23.2
  #   commands:
  #     - source /.env
  #     - COMPOSE_PROJECT_NAME=project-drone DRONE_GITHUB_CLIENT_ID=$DRONE_GITHUB_CLIENT_ID DRONE_GITHUB_CLIENT_SECRET=$DRONE_GITHUB_CLIENT_SECRET docker-compose -f docker-compose.drone.yml up -d --build
  #   volumes:
  #     - name: dockersock
  #       path: /var/run/docker.sock
  #     - name: drone_env
  #       path: /.env
        


volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: drone_env
    host:
      path: /home/data/config/drone/.env