version: "2.4"
services:

  wger_proxy:
    image: caddy
    container_name: wger_proxy
    restart: unless-stopped
    volumes:
      - ./wger/Caddyfile:/etc/caddy/Caddyfile
      - ${CONFIG_DIR}/wger/caddy_data:/data
      - ${CONFIG_DIR}/wger/caddy_config:/config
      - ${CONFIG_DIR}/wger/static:/static
      - ${CONFIG_DIR}/wger/media:/media
    
  wger:
    image: wger/server:latest
    container_name: wger
    depends_on:
      wger_db:
        condition: service_healthy
      wger_cache:
        condition: service_healthy
    env_file:
      - .env.wger
    volumes:
      - ${CONFIG_DIR}/wger/static:/home/wger/static
      - ${CONFIG_DIR}/wger/media:/home/wger/media
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped  

  wger_db:
    image: postgres:15-alpine
    container_name: wger_db
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
    volumes:
      - ${CONFIG_DIR}/wger/db:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  wger_cache:
    image: redis
    container_name: wger_cache
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  celery_worker:
    image: wger/server:latest
    container_name: wger_celery_worker
    command: /start-worker
    env_file:
      - .env.wger
    depends_on:
      wger_cache:
        condition: service_healthy
      wger_db:
        condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5

  celery_beat:
    image: wger/server:latest
    container_name: wger_celery_beat
    command: /start-beat
    volumes:
      - ${CONFIG_DIR}/wger/celery-beat:/home/wger/beat/
    env_file:
      - .env.wger
    depends_on:
      wger_cache:
        condition: service_healthy
