version: '3.5'
services:
  plex:
    container_name: plex
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: plexinc/pms-docker:latest
    hostname: Artemis
    environment:
      - TZ=Europe/Paris
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${BASE_DIR}/plex/transcode:/transcode
      - ${BASE_DIR}/plex/media/Shows:/data/shows
      - ${BASE_DIR}/plex/media/Movies:/data/movies
      - ${BASE_DIR}/plex/media/Anime:/data/anime
      - ${BASE_DIR}/transmission/completed:/data/completed
    restart: unless-stopped

  download:
    container_name: download
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    image: filebrowser/filebrowser:v1.11.0
    command: "--auth.method='none' --defaults.allowNew=false --defaults.allowCommands=false"
    volumes:
      - ${BASE_DIR}/transmission:/srv/transmission
      - ${BASE_DIR}/plex/media/Movies:/srv/movies
      - ${BASE_DIR}/plex/media/Shows:/srv/tv
      - ${BASE_DIR}/plex/media/Anime:/srv/anime
      - ${CONFIG_DIR}/download/config.json:/etc/config.json
      - ${CONFIG_DIR}/download/database.db:/etc/database.db
    restart: unless-stopped

  tautulli:
    container_name: tautull
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: linuxserver/tautulli
    links:
      - plex
    environment:
      - TZ=Europe/Paris
      - PGID=0
      - PUID=0
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
      - ${BASE_DIR}/tautulli/logs:/logs:ro
    restart: unless-stopped


  wireguard-azire:
    container_name: wireguard-azire
    privileged: true
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    build:
      context: ./wireguard-azire
    environment:
      - AZIRE_USERNAME=${AZIRE_USERNAME}
      - AZIRE_PASSWORD=${AZIRE_PASSWORD}
      - AZIRE_LOCATION=${AZIRE_LOCATION}
    volumes:
      - /etc/wireguard:/etc/wireguard
      - /lib/wireguard:/lib/wireguard
      - /lib/modules:/lib/modules
    ports:
      - 5555:5555
      - '51413:51413/tcp'
      - '51413:51413/udp'
    sysctls:
        - net.ipv4.conf.all.rp_filter=2
        - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always


  transmission:
    container_name: transmission
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    build:
      context: ./transmission
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - ${BASE_DIR}/transmission:/downloads
      - ${CONFIG_DIR}/transmission:/config/transmission
    restart: always
    depends_on:
      - wireguard-azire
    network_mode: "service:wireguard-azire"

  sonarr:
    container_name: sonarr
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: linuxserver/sonarr
    depends_on:
      - transmission
    links: 
      - jackett
      - plex
    volumes:            
      - ${CONFIG_DIR}/sonarr:/config
      - ${BASE_DIR}/plex/media/Shows:/tv
      - ${BASE_DIR}/plex/media/Anime:/anime
      - ${BASE_DIR}/transmission:/downloads
    environment:
      - PGID=0
      - PUID=0
      - TZ=Europe/London
    restart: unless-stopped

  radarr:
    container_name: radarr
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: linuxserver/radarr
    depends_on:
      - transmission
    links: 
      - jackett
      - plex
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${BASE_DIR}/plex/media/Movies:/movies
      - ${BASE_DIR}/plex/media/Anime:/anime
      - ${BASE_DIR}/transmission:/downloads
    environment:
      - PGID=0
      - PUID=0
      - TZ=Europe/London
    restart: unless-stopped

  jackett:
    container_name: jackett
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: linuxserver/jackett
    restart: always
    environment:
      - PGID=0
      - PUID=0
      - TZ=Europe/London
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${BASE_DIR}/jackett/downloads:/downloads
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: linuxserver/bazarr
    restart: always
    environment:
      - PGID=0
      - PUID=0
      - TZ=Europe/London
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${BASE_DIR}/bazarr/downloads:/downloads
      - ${BASE_DIR}/plex/media/Movies:/movies
      - ${BASE_DIR}/plex/media/Anime:/anime
      - ${BASE_DIR}/plex/media/Shows:/tv
      - ${BASE_DIR}/transmission:/downloads
    links:
      - sonarr
      - radarr
    deploy:
      resources:
        limits:
          cpus: '0.2'
    restart: unless-stopped

  portainer:
    container_name: portainer
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock --no-auth
    volumes:
      - ${BASE_DIR}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  lazylibrarian:
    container_name: lazylibrarian
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: linuxserver/lazylibrarian
    restart: always
    depends_on:
      - transmission
    environment:
      - PGID=0
      - PUID=0
      - TZ=Europe/London
    links: 
      - jackett
      - plex
      - calibre
    volumes:
      - ${CONFIG_DIR}/lazylibrarian:/config
      - ${BASE_DIR}/lazylibrarian/downloads:/downloads
      - ${BASE_DIR}/plex/media/Books:/books
      - ${BASE_DIR}/plex/media/Calibre:/Calibre
      - ${BASE_DIR}/transmission:/downloads
    restart: unless-stopped

  calibre:
    container_name: calibre
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: aptalca/docker-rdp-calibre
    restart: always
    environment:
      - PGID=0
      - PUID=0
      - EDGE=0
      - WIDTH=1280
      - HEIGHT=720
      - LIBRARYINTERNALPATH=/Calibre
      - TZ=Europe/London
    links: 
      - jackett
    volumes:
      - ${CONFIG_DIR}/calibre:/config
      - ${BASE_DIR}/plex/media/Books:/books
      - ${BASE_DIR}/plex/media/Calibre:/Calibre
    restart: unless-stopped

  organizr:
    container_name: organizr
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: tronyx/docker-organizr-v2
    restart: unless-stopped
    volumes:
        - ${CONFIG_DIR}/organizr:/config
    links:
      - admin
      - download
      - wireguard-azire
      - jackett
      - portainer
      - sonarr
      - radarr
      - plex
      - bazarr
      - lazylibrarian
    external_links:
      - drone
    networks: 
      - default
      - dronenet
    environment:
      - TZ=Europe/London

  ftpd:
    container_name: ftpd
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    image: stilliard/pure-ftpd:hardened
    restart: unless-stopped
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "${BASE_DIR}/ftpd:/home/user"
      - "${CONFIG_DIR}/ftpd/passwd:/etc/pure-ftpd/passwd"
      - "${CONFIG_DIR}/ftpd/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: thenairn.com
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: /home/user

  admin:
    container_name: admin
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    image: filebrowser/filebrowser:v1.11.0
    command: "--auth.method='none'"
    volumes:
      - ${BASE_DIR}/transmission:/srv/transmission
      - ${BASE_DIR}/plex/media/Movies:/srv/movies
      - ${BASE_DIR}/plex/media/Shows:/srv/tv
      - ${BASE_DIR}/plex/media/Anime:/srv/anime
      - ${BASE_DIR}/ftpd:/srv/camera
      - ${CONFIG_DIR}/admin/config.json:/etc/config.json
      - ${CONFIG_DIR}/admin/database.db:/etc/database.db
    restart: unless-stopped

  dwarffortress:
    container_name: dwarffortress
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    image: mifki/dfremote
    volumes:
      - ${BASE_DIR}/dwarffortress:/df_linux/data/save
    environment:
      DFREMOTE_PWD: ${DF_PASSWORD}
    ports:
      - "1235:1235/udp"
    restart: unless-stopped

  
  monica:
    image: monicahq/monicahq
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    links:
      - monicadb
    environment:
      - APP_KEY=${MONICA_APP_KEY}
      - DB_HOST=monicadb
      - APP_TRUSTED_PROXIES=
      - APP_TRUSTED_CLOUDFLARE=false
      - APP_ENV=production
    volumes:
      - ${BASE_DIR}/monica/app:/var/www/monica/storage
    restart: always

  monicadb:
    image: mysql:5.7
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    environment:
      - MYSQL_ROOT_PASSWORD=${MONICA_DB_ROOT_PW}
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - ${BASE_DIR}/monica/db:/var/lib/mysql
    restart: always

  caddy:
    container_name: caddy
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    environment:
      - TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}
    build:
      context: ./caddy
      args:
        plugins: reauth
    links:
      - download
      - admin
      - wireguard-azire
      - jackett
      - portainer
      - sonarr
      - radarr
      - organizr
      - plex
      - tautulli
      - bazarr
      - lazylibrarian
      - calibre
      - monica
    external_links:
      - drone
      - homepage
    networks: 
      - default
      - dronenet
      - homenet
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - ${BASE_DIR}/caddy:/root/.caddy
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10800 --label-enable --cleanup
    environment:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}

networks:
  dronenet:
    name: dronenet
  homenet:
    name: homenet