version: "2.4"
services:
  stirlingpdf:
    container_name: stirlingpdf
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    volumes:
      - ${CONFIG_DIR}/stirlingpdf/data:/usr/share/tessdata:rw
      - ${CONFIG_DIR}/stirlingpdf/config:/configs:rw
      - ${CONFIG_DIR}/stirlingpdf/logs:/logs:rw
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      SECURITY_ENABLELOGIN: "false"
      LANGS: "en_GB,en_US,ar_AR,de_DE,fr_FR,es_ES,zh_CN,zh_TW,ca_CA,it_IT,sv_SE,pl_PL,ro_RO,ko_KR,pt_BR,ru_RU,el_GR,hi_IN,hu_HU,tr_TR,id_ID"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: Stirling-PDF
      UI_HOMEDESCRIPTION: Demo site for Stirling-PDF Latest
      UI_APPNAMENAVBAR: Stirling-PDF Latest
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "true"
    restart: on-failure:5