version: "2.4"
services:
  vscode:
    container_name: vscode
    labels:
      plugsy.name: 'VSCode'
      plugsy.category: 'Code'
      plugsy.icon: '@styled-icons/simple-icons/Visualstudiocode'
      plugsy.link: https://code.thenairn.com
    image: linuxserver/code-server:4.95.1
    volumes:
      - ${DOWNLOADS_DIR}:/srv/Downloads
      - ${CONFIG_DIR}/vscode:/config
      - ${BOOT_DIR}:/ServerBoot
      - ${CONFIG_DIR}:/ServerConfig
      - ${INTERNAL_DIR}:/Internal:cached
      - /boot/.ssh:/config/host/.ssh:ro
      - /boot/.aws:/config/host/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GPG_PASSPHRASE=${VSCODE_GPG_PASSPHRASE}
      - PGID=0
      - PUID=0
      - PROXY_DOMAIN=code.thenairn.com
      - DOCKER_MODS=linuxserver/mods:code-server-zsh|linuxserver/mods:universal-docker|linuxserver/mods:code-server-shellcheck|inlustra/docker-mods:1password|inlustra/docker-mods:dotfiles|bambam018/docker-mod-java17|linuxserver/mods:code-server-terraform
      - DEFAULT_WORKSPACE=/Internal/thenairn.com
    restart: unless-stopped

  port-permission-module:
    container_name: port-permission-module
    image: port-permission-module
    build:
      context: ./caddy/port-permission-module
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - MIN_VALUE=1000 # Change this to your desired minimum value
      - MAX_VALUE=4000 # Change this to your desired maximum value
    restart: unless-stopped

  caddy:
    container_name: caddy
    environment:
      - PORKBUN_API_KEY=${PORKBUN_API_KEY}
      - PORKBUN_SECRET_KEY=${PORKBUN_SECRET_KEY}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      - JWT_SHARED_KEY=${JWT_SHARED_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - RCLONE_AUTH_TOKEN=${RCLONE_AUTH_TOKEN}
      - INVOICE_NINJA_ROOT=/invoiceninja
      - TLS_PERMISSION_ENDPOINT=http://port-permission-module:8000/check
    build:
      context: ./caddy
    links:
      - sonarr
      - radarr
      - plex
      - plugsy
      - prowlarr
      - overseerr
      - paperless
      - rclone
      - invoiceninja
      - port-permission-module
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - 9091:9091
    volumes:
      - ${CONFIG_DIR}/caddy/www:/root/.caddy
      - ${CONFIG_DIR}/caddy/certs:/caddy/certs
      - ${CONFIG_DIR}/caddy2/data:/data
      - ${CONFIG_DIR}/caddy2/config:/config
      - ${CONFIG_DIR}/invoiceninja:/var/www/app
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Playground:/Playground
    restart: unless-stopped

  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WUD_TRIGGER_SLACK_SLACK_TOKEN=${WUD_SLACK_TOKEN}
      - WUD_TRIGGER_SLACK_SLACK_CHANNEL=${WUD_SLACK_CHANNEL}
      - WUD_REGISTRY_LSCR_PUBLIC_USERNAME=Inlustra
      - WUD_REGISTRY_LSCR_PUBLIC_TOKEN=${WUD_GITHUB_TOKEN}
      - TZ=Europe/Paris

  paperless-broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/paperless-redis:/data

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    labels: 
      plugsy.name: 'Paperless'
      plugsy.category: 'Home'
      plugsy.icon: '@styled-icons/bootstrap/Paperclip'
      plugsy.link: https://docs.thenairn.com
    depends_on: 
      - paperless-broker
    environment:
      USERMAP_UID: 0
      USERMAP_GID: 0
      PAPERLESS_REDIS: redis://paperless-broker:6379
      TZ: Europe/Paris
      PAPERLESS_TIMEZONE: Europe/Paris
      DOCKER_MODS: linuxserver/mods:papermerge-multilangocr
      OCRLANG: fra,eng
      PAPERLESS_CONSUMPTION_DIR: /data/consume
      PAPERLESS_CONSUMER_POLLING: 20
      PAPERLESS_CONSUMER_RECURSIVE: 1
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: 1
      PAPERLESS_URL: "https://docs.thenairn.com"
      PAPERLESS_DATA_DIR: "/config"
      PAPERLESS_MEDIA_ROOT: "/data/media"
    volumes:
      - ${CONFIG_DIR}/paperless:/config
      - ${SCANS_DIR}:/data/consume
      - ${PAPERLESS_DOCS_DIR}:/data/media

  plugsy:
    container_name: plugsy
    image: plugsy/core:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./autodash.json:/config.json

  rclone: 
    container_name: rclone
    image: rclone/rclone:latest
    restart: unless-stopped
    command: rcd -vvv --rc-web-gui --rc-serve --rc-user=${RCLONE_USERNAME} --rc-pass=${RCLONE_PASSWORD} --rc-allow-origin="https://rclone.thenairn.com" --rc-web-gui-no-open-browser --rc-addr 0.0.0.0:5775
    volumes:
      - ${CONFIG_DIR}/rclone:/config/rclone
      - ${CONFIG_DIR}:/bkps/config
      - ${PAPERLESS_DOCS_DIR}:/bkps/paperless

  weddingphotos:
    container_name: weddingphotos
    image: inlustra/the-photo-gallery:0.0.4
    #To build from source, comment previous line and uncomment next line
    volumes:
      - /mnt/user/PersonalMedia/Wedding/original:/app/public/photos
      - /mnt/user/PersonalMedia/Wedding/storage:/app/storage
    environment:
      PAGE_TITLE: 'Nairn Wedding 2022'
      PAGE_HEADER_TEXT: '03/09/2022'
      PAGE_SHOW_FULLSCREEN_BUTTON: 'true'
      NODE_DISABLE_BLUR_GENERATION: 'true'
      DISABLE_CACHE: 'true'
    restart: unless-stopped

  gallery:
    container_name: gallery
    image: inlustra/the-photo-gallery:0.0.3
    #To build from source, comment previous line and uncomment next line
    volumes:
      - /mnt/user/Internal/thenairn.com/gallery/photos:/app/public/photos
      - /mnt/user/Internal/thenairn.com/gallery/storage:/app/storage
    environment:
      PAGE_TITLE: 'Example Gallery'
      PAGE_HEADER_TEXT: 'Example Gallery'
      PAGE_SHOW_FULLSCREEN_BUTTON: 'true'
      PHOTO_DEFAULT_REVERSE: 'false'
    restart: unless-stopped
