version: "2.4"
services:
  vscode:
    container_name: vscode
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      plugsy.name: 'VSCode'
      plugsy.category: 'Code'
      plugsy.icon: '@styled-icons/simple-icons/Visualstudiocode'
      plugsy.link: https://code.thenairn.com
    image: linuxserver/code-server:4.13.0
    volumes:
      - ${DOWNLOADS_DIR}:/srv/Downloads
      - ${CONFIG_DIR}/vscode:/config
      - ${BOOT_DIR}:/ServerBoot
      - ${CONFIG_DIR}:/ServerConfig
      - ${INTERNAL_DIR}:/Internal:cached
      - /boot/.ssh:/config/host/.ssh:ro
      - /boot/.aws:/config/host/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GPG_PASSPHRASE=${VSCODE_GPG_PASSPHRASE}
      - PGID=0
      - PUID=0
      - PROXY_DOMAIN=code.thenairn.com
      - DOCKER_MODS=linuxserver/mods:code-server-zsh|linuxserver/mods:universal-docker|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-shellcheck|inlustra/docker-mods:gcloudcli|inlustra/docker-mods:kubectl-helm|inlustra/docker-mods:dotfiles|bambam018/docker-mod-java17|linuxserver/mods:code-server-terraform
      - KEYBASE_USERNAME
      - KEYBASE_PAPERKEY
      - KEYBASE_DEVICE_NAME=vscode
      - DEFAULT_WORKSPACE=/Internal/thenairn.com
    restart: unless-stopped

  host:
    container_name: host
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    labels: 
      plugsy.name: 'Frigate'
      plugsy.category: 'Home'
      plugsy.icon: '@styled-icons/boxicons-regular/Cctv'
      plugsy.link: 'https://frigate.thenairn.com'
    image: ghcr.io/blakeblackshear/frigate:stable
    ports: 
      - '1935:1935'
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/frigate:/config
      - ${CAMERA_DIR}/frigate:/clips      
      - ${CAMERA_DIR}/frigate:/media/frigate      
      - type: tmpfs # 1GB of memory, reduces SSD/SD Card wear
        target: /cache
        tmpfs:
          size: 100000000
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget" , "-q", "-O-", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3m

  caddy:
    container_name: caddy
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    environment:
      - GANDI_API_KEY=${GANDI_API_KEY}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      - JWT_SHARED_KEY=${JWT_SHARED_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - RCLONE_AUTH_TOKEN=${RCLONE_AUTH_TOKEN}
      - INVOICE_NINJA_ROOT=/invoiceninja
    build:
      context: ./caddy
    links:
      - bitwarden
      - host
      - sonarr
      - radarr
      - plex
      - frigate
      - plugsy
      - prowlarr
      - overseerr
      - paperless
      - rclone
      - invoiceninja
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - 9091:9091
    volumes:
      - ${CONFIG_DIR}/caddy/www:/root/.caddy
      - ${CONFIG_DIR}/caddy/certs:/caddy/certs
      - ${CONFIG_DIR}/caddy2/data:/data
      - ${CONFIG_DIR}/caddy2/config:/config
      - ${CONFIG_DIR}/invoiceninja:/var/www/app
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Playground:/Playground
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10800 --label-enable --cleanup
    environment:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}

  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    labels: 
      plugsy.name: 'BitWarden'
      plugsy.category: 'Home'
      plugsy.icon: '@styled-icons/simple-icons/Bitwarden'
      plugsy.link: https://vault.thenairn.com
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN}
      - DOMAIN=${BITWARDEN_DOMAIN}
      
      - SMTP_HOST=${MAIL_HOST}
      - SMTP_FROM=vault@thenairn.com
      - SMTP_PORT=${MAIL_PORT}
      - SMTP_SSL=false
      - SMTP_USERNAME=${MAIL_USERNAME}
      - SMTP_EXPLICIT_TLS=true
      - SMTP_PASSWORD=${MAIL_PASSWORD}
      - SMTP_AUTH_MECHANISM="Login"

      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=false
    volumes:
      - ${CONFIG_DIR}/bw-data/:/data/

  paperless:
    image: lscr.io/linuxserver/paperless-ngx:latest
    container_name: paperless
    labels: 
      plugsy.name: 'Paperless'
      plugsy.category: 'Home'
      plugsy.icon: '@styled-icons/bootstrap/Paperclip'
      plugsy.link: https://docs.thenairn.com
    environment:
      PGID: 0
      PUID: 0
      TZ: Europe/Paris
      DOCKER_MODS: linuxserver/mods:papermerge-multilangocr
      OCRLANG: fra,eng
      PAPERLESS_CONSUMER_RECURSIVE: 1
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: 1
      PAPERLESS_URL: "https://docs.thenairn.com"
    volumes:
      - ${CONFIG_DIR}/paperless:/config
      - ${SCANS_DIR}:/data/consume
      - ${PAPERLESS_DOCS_DIR}:/data/media

  plugsy:
    container_name: plugsy
    image: plugsy/core:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./autodash.json:/config.json

  rclone: 
    container_name: rclone
    image: rclone/rclone:latest
    restart: unless-stopped
    command: rcd -vvv --rc-web-gui --rc-serve --rc-user=${RCLONE_USERNAME} --rc-pass=${RCLONE_PASSWORD} --rc-allow-origin="https://rclone.thenairn.com" --rc-web-gui-no-open-browser --rc-addr 0.0.0.0:5775
    volumes:
      - ${CONFIG_DIR}/rclone:/config/rclone
      - ${CONFIG_DIR}:/bkps/config
      - ${PAPERLESS_DOCS_DIR}:/bkps/paperless

  weddingphotos:
    container_name: weddingphotos
    image: inlustra/the-photo-gallery:0.0.4
    #To build from source, comment previous line and uncomment next line
    volumes:
      - /mnt/user/PersonalMedia/Wedding/original:/app/public/photos
      - /mnt/user/PersonalMedia/Wedding/storage:/app/storage
    environment:
      PAGE_TITLE: 'Nairn Wedding 2022'
      PAGE_HEADER_TEXT: '03/09/2022'
      PAGE_SHOW_FULLSCREEN_BUTTON: 'true'
      NODE_DISABLE_BLUR_GENERATION: 'true'
      DISABLE_CACHE: 'true'
    restart: unless-stopped

  gallery:
    container_name: gallery
    image: inlustra/the-photo-gallery:0.0.3
    #To build from source, comment previous line and uncomment next line
    volumes:
      - /mnt/user/Internal/thenairn.com/gallery/photos:/app/public/photos
      - /mnt/user/Internal/thenairn.com/gallery/storage:/app/storage
    environment:
      PAGE_TITLE: 'Example Gallery'
      PAGE_HEADER_TEXT: 'Example Gallery'
      PAGE_SHOW_FULLSCREEN_BUTTON: 'true'
      PHOTO_DEFAULT_REVERSE: 'false'
    restart: unless-stopped
