version: "2.4"
services:
  plex:
    runtime: nvidia
    container_name: plex
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      dockerDash.name: 'Plex'
      dockerDash.category: 'Media'
      dockerDash.icon: '@styled-icons/simple-icons/Plex'
      dockerDash.link: https://plex.thenairn.com
    image: plexinc/pms-docker:latest
    hostname: Artemis
    environment:
      - TZ=Europe/Paris
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
      - NVIDIA_VISIBLE_DEVICES=GPU-c1d14a88-b2fa-5786-e47d-64af7a34ea34
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /tmp:/transcode
      - ${CONFIG_DIR}/plex:/config
      - ${AMEDIA_DIR}/A:/data/ashows
      - ${MEDIA_DIR}/Shows:/data/shows
      - ${MEDIA_DIR}/Movies:/data/movies
      - ${MEDIA_DIR}/Anime:/data/anime
      - ${MEDIA_DIR}/Audiobooks:/data/audiobooks
      - ${PERSONAL_MEDIA_DIR}/:/data/personal
    restart: unless-stopped

  vscode:
    container_name: vscode
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      dockerDash.name: 'VSCode'
      dockerDash.category: 'Code'
      dockerDash.icon: '@styled-icons/simple-icons/Visualstudiocode'
      dockerDash.link: https://code.thenairn.com
    build:
      context: ./vscode
    volumes:
      - ${DOWNLOADS_DIR}:/srv/Downloads
      - ${CONFIG_DIR}/vscode:/config
      - ${BOOT_DIR}:/ServerBoot
      - /root/.ssh:/config/.ssh
      - ${INTERNAL_DIR}:/Internal:cached
      - ${CONFIG_DIR}:/ServerConfig
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GPG_PASSPHRASE=${VSCODE_GPG_PASSPHRASE}
      - PGID=0
      - PUID=0
      - PROXY_DOMAIN=code.thenairn.com
      - DOCKER_MODS=linuxserver/mods:code-server-docker|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-shellcheck
    
    restart: unless-stopped

  proxy:
    container_name: proxy
    image: jeroenslot/nordvpn-proxy
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USERNAME=${NORD_USERNAME}     # Required
      - PASSWORD=${NORD_PASSWORD}        # Required
      - COUNTRY=NL
      - LOCAL_NETWORK=192.168.96.0/24   
    volumes:
      - ${CONFIG_DIR}/proxy:/app/ovpn/config 

  transmission:
    container_name: transmission
    cap_add:
        - NET_ADMIN
    volumes:
        - ${DOWNLOADS_DIR}/incomplete:/data/downloads
        - ${DOWNLOADS_DIR}/completed:/data/completed
        - ${CONFIG_DIR}/transmission:/data/transmission-home
        - ${DOWNLOADS_DIR}:/data
    environment:
        - OPENVPN_PROVIDER=NORDVPN
        - NORDVPN_COUNTRY=NL
        - OPENVPN_USERNAME=${NORD_USERNAME}
        - OPENVPN_PASSWORD=${NORD_PASSWORD}
        - LOCAL_NETWORK=192.168.0.0/16
        - TRANSMISSION_WEB_UI=flood-for-transmission
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    image: haugene/transmission-openvpn
    restart: always

  sonarr:
    container_name: sonarr
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      dockerDash.name: 'Sonarr'
      dockerDash.category: 'Media'
      dockerDash.icon: '@styled-icons/feather/Tv'
      dockerDash.link: https://sonarr.thenairn.com
    image: linuxserver/sonarr:latest
    depends_on:
      - transmission
    links:
      - plex
      - gaps
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}/Shows:/tv
      - ${MEDIA_DIR}/Anime:/anime
      - ${AMEDIA_DIR}/A:/amedia
      - ${DOWNLOADS_DIR}/completed:/completed
    environment:
      - PGID=0
      - PUID=0
      - TZ=Europe/London
    restart: unless-stopped

  radarr:
    container_name: radarr
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      dockerDash.name: 'Radarr'
      dockerDash.category: 'Media'
      dockerDash.icon: '@styled-icons/feather/Film'
      dockerDash.link: https://radarr.thenairn.com
    image: linuxserver/radarr
    depends_on:
      - transmission
    links:
      - gaps
      - plex
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}/Movies:/movies
      - ${MEDIA_DIR}/Anime:/anime
      - ${DOWNLOADS_DIR}/completed:/completed
    environment:
      - PGID=0
      - PUID=0
      - TZ=Europe/London
    restart: unless-stopped

  admin:
    container_name: admin
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      dockerDash.name: 'File Manager'
      dockerDash.category: 'Media'
      dockerDash.icon: '@styled-icons/icomoon/FilesEmpty'
      dockerDash.link: https://download.thenairn.com
    image: filebrowser/filebrowser:v1.11.0
    command: "--auth.method='none'"
    volumes:
      - ${DOWNLOADS_DIR}:/srv/Downloads
      - ${MEDIA_DIR}:/srv/Media
      - ${AMEDIA_DIR}:/srv/AMedia
      - ${INTERNAL_DIR}:/srv/Internal
      - ${BACKUP_DIR}:/srv/Backup
      - ${CONFIG_DIR}/admin/config.json:/etc/config.json
      - ${CONFIG_DIR}/admin/database.db:/etc/database.db
    restart: unless-stopped

  dwarffortress:
    container_name: dwarffortress
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      dockerDash.name: 'Dwarf Fortress'
      dockerDash.category: 'Games'
      dockerDash.icon: '@styled-icons/boxicons-regular/Game'
    image: mifki/dfremote
    volumes:
      - ${CONFIG_DIR}/dwarffortress:/df_linux/data/save
    environment:
      DFREMOTE_PWD: ${DF_PASSWORD}
    ports:
      - "1235:1235/udp"
    restart: unless-stopped

  host:
    container_name: host
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    labels: 
      dockerDash.name: 'Frigate'
      dockerDash.category: 'Home'
      dockerDash.icon: '@styled-icons/boxicons-regular/Cctv'
      dockerDash.link: 'https://frigate.thenairn.com'
    image: blakeblackshear/frigate:stable-amd64
    ports: 
      - '1935:1935'
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/frigate:/config
      - ${CAMERA_DIR}/frigate:/clips      
      - ${CAMERA_DIR}/frigate:/media/frigate      
      - type: tmpfs # 1GB of memory, reduces SSD/SD Card wear
        target: /cache
        tmpfs:
          size: 100000000
    healthcheck:
      test: ["CMD", "wget" , "-q", "-O-", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3m

  caddy:
    container_name: caddy
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    environment:
      - GANDI_API_KEY=${GANDI_API_KEY}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
    build:
      context: ./caddy
    links:
      - bitwarden
      - host
      - admin
      - sonarr
      - radarr
      - plex
      - frigate
      - vikunjaapi
      - vikunjafrontend
      - teedy
      - plugsy
      - prowlarr
      - overseerr
      - gaps
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - 9091:9091
    volumes:
      - ${CONFIG_DIR}/caddy/www:/root/.caddy
      - ${CONFIG_DIR}/caddy/certs:/caddy/certs
      - ${CONFIG_DIR}/caddy2/data:/data
      - ${CONFIG_DIR}/caddy2/config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Playground:/Playground
    volumes_from:
      - nextcloudapp
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    links:
      - sonarr
      - radarr
    volumes:
      - ${CONFIG_DIR}/overseer:/config
    restart: unless-stopped

  gaps:
    image: housewrecker/gaps
    container_name: gaps
    links:
      - plex
    volumes: 
      - ${CONFIG_DIR}/gaps:/usr/data

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10800 --label-enable --cleanup
    environment:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}

  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    labels: 
      dockerDash.name: 'BitWarden'
      dockerDash.category: 'Home'
      dockerDash.icon: '@styled-icons/simple-icons/Bitwarden'
      dockerDash.link: https://vault.thenairn.com
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN}
      - DOMAIN=${BITWARDEN_DOMAIN}
    volumes:
      - ${CONFIG_DIR}/bw-data/:/data/

  handbrake:
    runtime: nvidia
    image: zocker160/handbrake-nvenc:latest
    container_name: handbrake
    labels:
      dockerDash.name: 'Handbrake'
      dockerDash.category: 'Media'
      dockerDash.icon: '@styled-icons/material-outlined/MovieFilter'
      dockerDash.link: 'https://handbrake.thenairn.com'
    environment: 
      - NVIDIA_VISIBLE_DEVICES=GPU-c1d14a88-b2fa-5786-e47d-64af7a34ea34
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ${CONFIG_DIR}/handbrake/:/config/
      - ${MEDIA_DIR}:/storage/

  nextclouddb: 
    image: mariadb
    container_name: nextclouddb
    restart: unless-stopped
    labels:
      dockerDash.name: 'DB'
      dockerDash.icon: '@styled-icons/feather/Database'
      dockerDash.parents: 'Nextcloud'
    volumes:
      - ${NEXTCLOUD_DIR}/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASS}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

    
  nextcloudapp:
    image: nextcloud:fpm
    container_name: nextcloudapp
    restart: unless-stopped
    labels:
      dockerDash.name: 'Nextcloud'
      dockerDash.category: 'Home'
      dockerDash.icon: '@styled-icons/simple-icons/Nextcloud'
      dockerDash.link: 'https://cloud.thenairn.com/'
    links:
      - nextclouddb
    volumes:
      - ${NEXTCLOUD_DIR}/app:/var/www/html
      - ./nextcloudapp/settings.config.php:/var/www/html/config/settings.config.php
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextclouddb
    restart: unless-stopped

  vikunjadb:
    image: mariadb:10
    labels:
      dockerDash.name: 'DB'
      dockerDash.parents: 'Todo'
      dockerDash.icon: '@styled-icons/feather/Database'
    container_name: vikunjadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${VIKUNJA_DB_PASS}
      MYSQL_DATABASE: vikunja
    volumes:
      - ${CONFIG_DIR}/vikunja/db:/var/lib/mysql
    restart: unless-stopped
  vikunjaapi:
    labels:
      dockerDash.name: 'API'
      dockerDash.parents: 'Todo'
      dockerDash.icon: '@styled-icons/feather/Server'
    container_name: vikunjaapi
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: vikunjadb
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DB_PASS}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: root
      VIKUNJA_DATABASE_DATABASE: vikunja
    volumes: 
      - ${CONFIG_DIR}/vikunja/files:/app/vikunja/files
    links:
      - vikunjadb
    restart: unless-stopped
  vikunjafrontend:
    image: vikunja/frontend
    container_name: vikunjafrontend
    restart: unless-stopped
    labels:
      dockerDash.name: 'Todo'
      dockerDash.category: 'Home'
      dockerDash.icon: '@styled-icons/remix-fill/CalendarTodo'
      dockerDash.link: https://todo.thenairn.com

  teedy:
    container_name: teedy
    image: sismics/docs:v1.9
    restart: unless-stopped
    labels: 
      dockerDash.name: 'Docs'
      dockerDash.category: 'Home'
      dockerDash.icon: '@styled-icons/boxicons-solid/FilePdf'
      dockerDash.link: https://docs.thenairn.com
    environment:
      # Base url to be used
      DOCS_BASE_URL: "https://docs.thenairn.com"
      # Set the admin email
      DOCS_ADMIN_EMAIL_INIT: ${TEEDY_ADMIN_EMAIL}
      # Set the admin password (in this example: "superSecure")
      DOCS_ADMIN_PASSWORD_INIT: ${TEEDY_ADMIN_PASSWORD}
    volumes:
      - ${NEW_DOCS_DIR}:/data
      
  teedy-import-uk:
    container_name: teedy-import-uk
    restart: unless-stopped
    labels:
      dockerDash.name: 'Importer: UK'
      dockerDash.parents: 'Docs'
      dockerDash.icon: '@styled-icons/material-outlined/Scanner'
    environment:
        - TEEDY_ADDTAGS=false
        - TEEDY_LANG=eng
        - 'TEEDY_URL=https://docs.thenairn.com'
        - TEEDY_USERNAME=${TEEDY_USERNAME}
        - TEEDY_PASSWORD=${TEEDY_PASSWORD}
    volumes:
        - '/mnt/user/Scans/English:/import'
    image: 'sismics/docs-importer:latest'
  teedy-import-fr:
    labels:
      dockerDash.name: 'Importer: FR'
      dockerDash.parents: 'Docs'
      dockerDash.icon: '@styled-icons/material-outlined/Scanner'
    container_name: teedy-import-fr
    restart: unless-stopped
    environment:
        - TEEDY_ADDTAGS=false
        - TEEDY_LANG=fra
        - 'TEEDY_URL=https://docs.thenairn.com'
        - TEEDY_USERNAME=${TEEDY_USERNAME}
        - TEEDY_PASSWORD=${TEEDY_PASSWORD}
    volumes:
        - '/mnt/user/Scans/French:/import'
    image: 'sismics/docs-importer:latest'

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/linuxserver/prowlarr:develop
    environment:
      PUID: 0
      PGID: 0
      TZ: Europe/London
      com.centurylinklabs.watchtower.enable: "false"
      dockerDash.name: 'Prowlarr'
      dockerDash.category: 'Media'
      dockerDash.icon: '@styled-icons/fluentui-system-filled/GlobeSearch'
      dockerDash.link: https://prowlarr.thenairn.com
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    restart: unless-stopped
    links:
      - sonarr
      - radarr
      - proxy
    
  plugsy:
    container_name: plugsy
    image: plugsy/core:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./autodash.json:/config.json
