services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    labels:
      plugsy.name: "Immich"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/feather/Image"
      plugsy.link: https://immich.thenairn.com
    volumes:
      - ${PERSONAL_MEDIA_DIR}/immich/upload:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env.immich
    depends_on:
      - immich-redis
      - immich-database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    labels:
      plugsy.name: "ML Engine"
      plugsy.parents: "Immich"
      plugsy.icon: "@styled-icons/feather/Cpu"
    volumes:
      - ${PERSONAL_MEDIA_DIR}/immich/ml:/cache
    env_file:
      - .env.immich
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:8e8d64b405ce18f41b8e5ee20aa4687a8ed0022d1298f2ce31cdcf3a76e09411
    labels:
      plugsy.name: "Redis Cache"
      plugsy.parents: "Immich"
      plugsy.icon: "@styled-icons/feather/Database"
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    labels:
      plugsy.name: "Database"
      plugsy.parents: "Immich"
      plugsy.icon: "@styled-icons/feather/Database"
    env_file:
      - .env.immich
    environment:
      DB_STORAGE_TYPE: "HDD"
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${PERSONAL_MEDIA_DIR}/immich/pgdata:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false

  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk:0.41.0
    container_name: immich-kiosk
    labels:
      plugsy.name: "Photo Frame"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/feather/Monitor"
      plugsy.link: https://frame.thenairn.com
    tty: true
    environment:
      LANG: "en_GB"
      TZ: "Europe/Paris"
    volumes:
      - ./immich-kiosk/config.yaml:/config/config.yaml
      - ${CONFIG_DIR}/immich-kiosk/config:/config
      # - ./custom.css:/custom.css
      # - ./offline-assets:/offline-assets
    restart: always